### PR TITLE
Change airship references

### PR DESCRIPTION
**Pull request by Xenwar**

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
Looks good.
I noticed some of the files were moved from `airship/*` to `metal3/airship/*`. Is it on purpose we keep airship in the path there?

**Comment by Xenwar** [comment]
> Looks good. I noticed some of the files were moved from `airship/*` to `metal3/airship/*`. Is it on purpose we keep airship in the path there?

Thanks. 
fixed it.

**Review by lentzi90 — APPROVED** [review]
LGTM!

**Review by furkatgofurov7 — COMMENTED** [review]
Thanks for cleanup @Xenwar!

I do not see the point of renaming markdown files under experiments folder here https://github.com/Nordix/metal3-clusterapi-docs/tree/master/airship/experiments since they are not visible properly on github and not sure why they were added. That's how it looks like when I checked on them:
image

**Comment by furkatgofurov7** [comment]
> In fact, the content under airship(now metal3) is not longer relevant.

Agree, +1 to remove it at all.

**Review by kashifest — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
> In fact, the content under airship(now metal3) is not longer relevant.

@Xenwar if agreed, let's remove the contents under the metal3 folder and get this in?

**Pull request merged**
